### ISSUE TITLE
csi restore catch error,  namespace cannot change when restore volumesnapshotcontents.snapshot.storage.k8s.io

### ISSUE THREAD

**Issue by ruanchen** [vmware-tanzu/velero-plugin-for-csi#75] opened 2020-10-29 07:09 UTC
**What's my use**
Velero Restore use namespaceMapping to recover data from one namespace to another namespace

**Problems**
When I use csi-plugin to restore PV data, when creaing volumesnapshotcontents.snapshot.storage.k8s.io
https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/main/internal/restore/volumesnapshot_action.go#L71 ,the namespace is still source namespace. So csi-plugin cannot create volumesnapshotcontents.snapshot.storage.k8s.io, and my recover is failed.

**Reason**
Velero use "action.Execute" to call the plugin, and then change to namespace to new. So csi-plugin's namespace data is old, we need change the namespace and other data if we need.

**Comment by ruanchen** [comment] 2020-11-05 02:31
@carlisia @joonas @dougm @aramprice can anyone check the issue?

**Comment by nrb** [comment] 2020-11-16 20:25
This is a duplicate of #77; we know it's a missing feature at the moment.

**Closed by nrb** 2020-11-16 20:25 UTC
Labels: duplicate

**Comment by ashish-amarnath** [comment] 2020-11-16 20:28
This is a known issue and we are tracking that at https://github.com/vmware-tanzu/velero/issues/2143
